services:
  aurral:
    build: .
    user: "0:0"
    ports:
      - "3001:3001"
    environment:
      - WEEKLY_FLOW_DOWNLOADS=/data/downloads/tmp
    volumes:
      - ./backend/data:/app/backend/data
      - /data/downloads/tmp:/app/weekly-flow
